//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class DemoScene : TypedScene
    {
        
        private const string GUID = "78addc77d730f4f38a4a7d5e73530376";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
