//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_2ddemo : TypedScene
    {
        
        private const string GUID = "0ef9b490e5d6bad4ea1935d07d1c2ea9";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
