//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_cards : TypedScene
    {
        
        private const string GUID = "855bb038b5077e74082152830a86f4fe";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
