//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_swordcombat2 : TypedScene
    {
        
        private const string GUID = "644eb321da943bd49b68667f53e4e1f1";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
