//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_money : TypedScene
    {
        
        private const string GUID = "da2a3050d66c3624884fce0e239e2ba6";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
