//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_fire : TypedScene
    {
        
        private const string GUID = "88a9ddda0ca72bb488c72771c26caba4";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
