//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_powerups2 : TypedScene
    {
        
        private const string GUID = "3fa05937c0d498e4688b6eb2ba76e5da";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
