//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_singleeffect : TypedScene
    {
        
        private const string GUID = "501ab33a8d23850479846415355a12b2";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
