//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_singleeffect_render : TypedScene
    {
        
        private const string GUID = "adcbb5e4c81028041bc317f42b44bc5a";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
