//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_fireworks : TypedScene
    {
        
        private const string GUID = "32ddbd81248ad9c43a2fc3edfba6e326";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
