//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_wind : TypedScene
    {
        
        private const string GUID = "565750a970c487a4280f95fd0ed4f9fc";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
