//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_emojis : TypedScene
    {
        
        private const string GUID = "b0de468b5dc93da4d8ee716d4782d2ba";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
