//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_portals2 : TypedScene
    {
        
        private const string GUID = "86778e72f0ca2294eb01df38043aa08e";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
