//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_explosions : TypedScene
    {
        
        private const string GUID = "f91c322868183cc4a96eb6242e73deac";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
