//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_missiles : TypedScene
    {
        
        private const string GUID = "b1d44d13576492049bc14b200e0d90cc";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
