//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_magic : TypedScene
    {
        
        private const string GUID = "1e1bb871721d63e4f92474359db37b3d";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
