//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_flares : TypedScene
    {
        
        private const string GUID = "e2bb5f0193a596246b4de5a53732a695";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
