//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_decal_test : TypedScene
    {
        
        private const string GUID = "6dad6ea22f37cdc4783ddb9f84d5fd4a";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
