//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_maindemo : TypedScene
    {
        
        private const string GUID = "8bd1bda334a6f2440817b9493f9d7703";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
