//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_portals : TypedScene
    {
        
        private const string GUID = "dc955c3e9f407e245a0d2d03086ef10c";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
