//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_explosions2 : TypedScene
    {
        
        private const string GUID = "23b30f55479243746a484e7a7ba74b29";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
