//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_magic3 : TypedScene
    {
        
        private const string GUID = "d70a7dcb427d83b48bd82c3e982e09b4";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
