//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_magic2 : TypedScene
    {
        
        private const string GUID = "c5094e256f2a7a04b913a7b17313517a";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
