//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_decals : TypedScene
    {
        
        private const string GUID = "5b495297bbe0d2549aa87a2ef68dd6f5";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
