//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_videopreview : TypedScene
    {
        
        private const string GUID = "455fd77e8f405b04c810d29ad2dff2db";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
