//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class etfx_healing : TypedScene
    {
        
        private const string GUID = "5dc0fb5f1c3c34d47baefa2a3c5f19e1";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
