//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class FantasyAxeAndShield_Scene : TypedScene
    {
        
        private const string GUID = "1690861171c5bda44bf8059d68e1b840";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
