//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class FantasyAxeAndShield_Scene : TypedScene
    {
        
        private const string GUID = "7ff26918cadf9254e8ebfb26fe58f0a3";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
