//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class FREE_StylizedWeaponsDEMO : TypedScene
    {
        
        private const string GUID = "1863f0e5608c76b4b9bb7fa6c4f661ec";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
