//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class Level_2 : TypedScene
    {
        
        private const string GUID = "10ee4fe5323704f47b1ecc8dcba5d908";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
        
        public static void Load(Script.Loader.InfoToLevel argument)
        {
            LoadScene(GUID, argument);
        }
    }
}
