//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class Level_4 : TypedScene
    {
        
        private const string GUID = "35a75c5110cfc8d4bb223c9e23beda5a";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
        
        public static void Load(Script.Loader.InfoToLevel argument)
        {
            LoadScene(GUID, argument);
        }
    }
}
