//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class MainMenu : TypedScene
    {
        
        private const string GUID = "3688284725bb9f646a69eba68a30765d";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
        
        public static void Load(Script.Loader.Info.InfoToMainMenu argument)
        {
            LoadScene(GUID, argument);
        }
    }
}
